/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PortaRetrato() {
  const { nodes, materials } = useGLTF("/Model3d/portaretratos2.glb");
  return (
    <group 
    //position={[-1.5, -0.7, 2.7]} 
    //rotation={[0.2,0.3,-0.05]}
    dispose={null}>
      <mesh
        name="portada"
        castShadow
        receiveShadow
        geometry={nodes.portada.geometry}
        material={materials['Material predeterminado.001']}
        position={[0.041, 0.846, 0.001]}
        rotation={[0.139, -1.534, -1.191]}
        scale={[7.802, 0.377, 5.177]}
      />
      <group
        name="estructura"
        position={[0.042, 0.857, 0.009]}
        rotation={[0, -1.536, -1.33]}
        scale={[0.408, 0.642, 5.732]}>
        <mesh
          name="default_procedural_mesh_cube#004"
          castShadow
          receiveShadow
          geometry={nodes['default_procedural_mesh_cube#004'].geometry}
          material={materials['Black Matte Ceramic.001']}
        />
        <mesh
          name="default_procedural_mesh_cube#004_1"
          castShadow
          receiveShadow
          geometry={nodes['default_procedural_mesh_cube#004_1'].geometry}
          material={materials['Black Matte Ceramic 2.001']}
        />
      </group>
      <mesh
        name="Cubo"
        castShadow
        receiveShadow
        geometry={nodes.Cubo.geometry}
        material={materials['Material.004']}
        position={[0.027, 1, -0.049]}
        rotation={[0, -1.536, 0]}
        scale={[1, 1, 11.165]}
      />
    </group>
  );
}

useGLTF.preload("/Model3d/portaretratos2.glb");
